# ML stock forecaster and caching module
import os
import pandas as pd
import numpy as np

CACHE_DIR = os.path.join(os.path.dirname(__file__), "models_cache")
os.makedirs(CACHE_DIR, exist_ok=True)

def predict_single(text: str):
    ticker = text.upper().strip()
    if len(ticker) < 1 or len(ticker) > 12 or not all(c.isalnum() or c in ".-" for c in ticker):
        return {"prediction": f"Invalid symbol/input: '{text}'. Please provide a valid stock ticker (e.g., AAPL or SBIN.NS).", "numeric": None}


    # Dynamic imports with fallback
    try:
        import yfinance as yf
        from sklearn.linear_model import LinearRegression
        from sklearn.model_selection import train_test_split
        from sklearn.metrics import mean_squared_error
        import joblib
    except ImportError:
        # Fallback Mock if ML libraries are not installed yet
        mock_price = 100.0 + (hash(ticker) % 250)
        predicted = mock_price * 1.025
        currency = "₹" if (ticker.endswith(".NS") or ticker.endswith(".BO")) else "$"
        
        # Generate mock historical data
        import datetime
        mock_historical = []
        today_date = datetime.date.today()
        for i in range(30, 0, -1):
            day = today_date - datetime.timedelta(days=i)
            p = mock_price + np.sin(i / 5.0) * 8 + (hash(ticker) % 15)
            mock_historical.append({"date": day.strftime("%Y-%m-%d"), "close": float(round(p, 2))})
            
        mock_meta = {
            "open": float(round(mock_price - 1.5, 2)),
            "high": float(round(mock_price + 4.2, 2)),
            "low": float(round(mock_price - 3.8, 2)),
            "volume": 2500000 + (hash(ticker) % 4000000),
            "currency": currency
        }
        
        return {
            "prediction": f"[Mock] Forecast for {ticker}: Latest: {currency}{mock_price:.2f} | Predicted Close: {currency}{predicted:.2f} (Install yfinance & scikit-learn for real ML prediction)",
            "numeric": float(round(predicted, 2)),
            "latest_data": mock_meta,
            "historical": mock_historical
        }

    model_path = os.path.join(CACHE_DIR, f"{ticker}.pkl")
    
    # Determine currency symbol based on ticker suffix
    currency = "$"
    if ticker.endswith(".NS") or ticker.endswith(".BO"):
        currency = "₹"
    elif ticker.endswith(".L"):
        currency = "£"
        
    try:
        # 1. Fetch data from yfinance with 5-second timeout
        data = yf.download(ticker, period="2y", interval="1d", timeout=5)
        if data.empty or len(data) < 20:
            raise ValueError("Empty or insufficient data returned from yfinance")
        
        # Focus on key price columns
        df = data[['Close', 'Open', 'High', 'Low', 'Volume']].copy()
        df = df.dropna()
        
        # Ensure 1D data format (flatten multi-index columns if generated by yfinance)
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)
            
        # 2. Preprocess: Predict next day close
        df['Prediction'] = df['Close'].shift(-1)
        
        # Features and labels
        X = np.array(df[['Close']][:-1])
        y = np.array(df['Prediction'][:-1])
        
        # Train-Test Split (sequential split for time-series)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
        
        # 3. Model Training
        model = LinearRegression()
        model.fit(X_train, y_train)
        
        # Cache trained model
        joblib.dump(model, model_path)
        
        # 4. Evaluation and prediction
        y_pred = model.predict(X_test)
        rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))
        
        last_price = float(df['Close'].iloc[-1].item())
        predicted_next = float(model.predict([[last_price]])[0])
        
        # 5. Extract latest stats
        latest = df.iloc[-1]
        latest_data = {
            "open": float(round(latest["Open"].item(), 2)) if hasattr(latest["Open"], "item") else float(round(latest["Open"], 2)),
            "high": float(round(latest["High"].item(), 2)) if hasattr(latest["High"], "item") else float(round(latest["High"], 2)),
            "low": float(round(latest["Low"].item(), 2)) if hasattr(latest["Low"], "item") else float(round(latest["Low"], 2)),
            "volume": int(latest["Volume"].item()) if hasattr(latest["Volume"], "item") else int(latest["Volume"]),
            "currency": currency
        }
        
        # 6. Extract 30-day historical prices
        historical_df = df.tail(30)
        historical_list = []
        for index, row in historical_df.iterrows():
            date_str = index.strftime("%Y-%m-%d") if hasattr(index, "strftime") else str(index)[:10]
            close_val = float(round(row["Close"].item(), 2)) if hasattr(row["Close"], "item") else float(round(row["Close"], 2))
            historical_list.append({"date": date_str, "close": close_val})
            
        return {
            "prediction": f"Forecast for {ticker}: Latest Close: {currency}{last_price:.2f} | Predicted Next Day: {currency}{predicted_next:.2f} (Model RMSE: {currency}{rmse:.2f})",
            "numeric": float(round(predicted_next, 2)),
            "latest_data": latest_data,
            "historical": historical_list
        }
    except Exception as e:
        # Smart fallback to mock prediction if download fails, times out, or has no internet connection
        mock_price = 100.0 + (hash(ticker) % 250)
        predicted = mock_price * 1.025
        
        # Generate mock historical data
        import datetime
        mock_historical = []
        today_date = datetime.date.today()
        for i in range(30, 0, -1):
            day = today_date - datetime.timedelta(days=i)
            p = mock_price + np.sin(i / 5.0) * 8 + (hash(ticker) % 15)
            mock_historical.append({"date": day.strftime("%Y-%m-%d"), "close": float(round(p, 2))})
            
        mock_meta = {
            "open": float(round(mock_price - 1.5, 2)),
            "high": float(round(mock_price + 4.2, 2)),
            "low": float(round(mock_price - 3.8, 2)),
            "volume": 2500000 + (hash(ticker) % 4000000),
            "currency": currency
        }
        
        return {
            "prediction": f"[Mock Fallback] Forecast for {ticker}: Latest: {currency}{mock_price:.2f} | Predicted Close: {currency}{predicted:.2f} (yfinance failed/timed out: {str(e)})",
            "numeric": float(round(predicted, 2)),
            "latest_data": mock_meta,
            "historical": mock_historical
        }



def predict_batch_from_df(df: pd.DataFrame, input_col: str):
    results = []
    for _, row in df.iterrows():
        inp = str(row[input_col])
        results.append(predict_single(inp))
    return results

